#!/bin/sh

rm -rf ./vendor/cboden/ratchet/tests
rm -rf ./vendor/cboden/ratchet/.travis.yml
rm -rf ./vendor/cboden/ratchet/CHANGELOG.md
rm -rf ./vendor/cboden/ratchet/composer.json
rm -rf ./vendor/cboden/ratchet/Makefile
rm -rf ./vendor/cboden/ratchet/phpunit.xml.dist
rm -rf ./vendor/cboden/ratchet/README.md
rm -rf ./vendor/evenement/evenement/doc
rm -rf ./vendor/evenement/evenement/examples
rm -rf ./vendor/evenement/evenement/tests
rm -rf ./vendor/evenement/evenement/.gitignore
rm -rf ./vendor/evenement/evenement/.travis.yml
rm -rf ./vendor/evenement/evenement/CHANGELOG.md
rm -rf ./vendor/evenement/evenement/composer.json
rm -rf ./vendor/evenement/evenement/phpunit.xml.dist
rm -rf ./vendor/evenement/evenement/README.md
rm -rf ./vendor/ratchet/pawl/tests
rm -rf ./vendor/ratchet/pawl/.gitignore
rm -rf ./vendor/ratchet/pawl/.travis.yml
rm -rf ./vendor/ratchet/pawl/composer.json
rm -rf ./vendor/ratchet/pawl/phpunit.xml.dist
rm -rf ./vendor/ratchet/pawl/README.md
rm -rf ./vendor/ratchet/rfc6455/tests
rm -rf ./vendor/ratchet/rfc6455/.gitignore
rm -rf ./vendor/ratchet/rfc6455/.travis.yml
rm -rf ./vendor/ratchet/rfc6455/composer.json
rm -rf ./vendor/ratchet/rfc6455/phpunit.xml.dist
rm -rf ./vendor/ratchet/rfc6455/README.md
rm -rf ./vendor/react/cache/tests
rm -rf ./vendor/react/cache/.gitignore
rm -rf ./vendor/react/cache/.travis.yml
rm -rf ./vendor/react/cache/CHANGELOG.md
rm -rf ./vendor/react/cache/composer.json
rm -rf ./vendor/react/cache/phpunit.xml.dist
rm -rf ./vendor/react/cache/README.md
rm -rf ./vendor/react/dns/tests
rm -rf ./vendor/react/dns/.gitignore
rm -rf ./vendor/react/dns/.travis.yml
rm -rf ./vendor/react/dns/CHANGELOG.md
rm -rf ./vendor/react/dns/composer.json
rm -rf ./vendor/react/dns/phpunit.xml.dist
rm -rf ./vendor/react/dns/README.md
rm -rf ./vendor/react/event-loop/CHANGELOG.md
rm -rf ./vendor/react/event-loop/composer.json
rm -rf ./vendor/react/event-loop/README.md
rm -rf ./vendor/react/promise/CHANGELOG.md
rm -rf ./vendor/react/promise/composer.json
rm -rf ./vendor/react/promise/README.md
rm -rf ./vendor/react/promise-timer/tests
rm -rf ./vendor/react/promise-timer/.gitignore
rm -rf ./vendor/react/promise-timer/.travis.yml
rm -rf ./vendor/react/promise-timer/CHANGELOG.md
rm -rf ./vendor/react/promise-timer/composer.json
rm -rf ./vendor/react/promise-timer/phpunit.xml.dist
rm -rf ./vendor/react/promise-timer/README.md
rm -rf ./vendor/react/socket/CHANGELOG.md
rm -rf ./vendor/react/socket/composer.json
rm -rf ./vendor/react/socket/README.md
rm -rf ./vendor/react/stream/CHANGELOG.md
rm -rf ./vendor/react/stream/composer.json
rm -rf ./vendor/react/stream/README.md